version: '3.8'

services:
  app:
    build: .
    container_name: devops2
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://localhost:5432/newcloud_db}
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: Password
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    container_name: newcloud
    environment:
      POSTGRES_USER: viccyn
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: newcloud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  fluentd:
    image: fluent/fluentd:v1.15-1
    container_name: fluentd
    ports:
       - "24224:24224"
       - "24220:24220" # Monitoring
    volumes:
      - ./fluentd/conf:/fluentd/etc/fluent.conf
      - /var/log:/var/log # Mount host log directory (optional)
    environment:
      FLUENTD_CONF: "fluent.conf"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.0.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
